[routers]
RT01 ansible_host=10.1.10.11
RT02 ansible_host=10.1.10.12

[routers:vars]
ansible_user=SUZUKI
ansible_password=CCNP
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
