---
# RT02 の BGP 設計データ（AS65002）。
bgp:
  as_number: "65002"
  router_id: 2.2.2.2
  neighbors:
    - neighbor_address: 10.1.12.1
      remote_as: "65001"
  af_networks:
    - address: 2.2.2.2
      mask: 255.255.255.255
  af_neighbors:
    - neighbor_address: 10.1.12.1
      activate: true
