# 対象ルータ（RT01〜RT03）。接続情報はこのレベルでは記入済み（穴は role 側）。
[routers]
RT01 ansible_host=10.1.10.11
RT02 ansible_host=10.1.10.12
RT03 ansible_host=10.1.10.13

[routers:vars]
ansible_user=SUZUKI
ansible_password=CCNP
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
